apps/adopcion/urls.py
from django.conf.urls import url, include
from apps.adopcion.views import index_adopcion

urlpatterns = [
    url(r'^$', index_adopcion),
]

apps/mascota/urls.py
from django.conf.urls import url, include
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', MascotaDelete.as_view(), name='mascota_eliminar'),
]

apps/usuario/urls.py
from django.conf.urls import url

from apps.usuario.views import RegistroUsuario

urlpatterns = [
	url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),

]

blog/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.post_list),
	]

misperris/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include ('apps.usuario.urls', namespace="usuario")),
    url(r'^$', include ('blog.urls', namespace="usuario")),
    url(r'', include('blog.urls')),
    url(r'^loguear/', login, {'template_name':'login.html'}, name='login'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

]

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    run = models.CharField(max_length=10)
    fNacimiento = models.DateField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    region = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    tipoVivienda = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona

# Create your models here.

class Mascota(models.Model):
    
    nombre = models.CharField(max_length=50)
    raza = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    descripcion = models.TextField()
    estado = models.CharField(max_length=10)
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}' .format(self.nombre, self.persona)
        #cadena = self.nombre+" adoptante: "+self.persona
        #return cadena

apps/usuario/models.py
from django.db import models

# Create your models here.

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota


class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'raza',
            'sexo',
			'descripcion',
            'estado',
			'persona',
			
		]
		labels = {
			'nombre': 'Nombre',
			'raza': 'Raza',
            'sexo': 'Sexo',
			'descripcion': 'Descripcion',
            'estado' : 'Estado',
			'persona': 'Adoptante',
			
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'raza': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion': forms.TextInput(attrs={'class':'form-control'}),
            'estado' : forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			
		}

apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistroForm(UserCreationForm):

	class Meta:
		model = User
		fields = [
				'username',
				'first_name',
				'last_name',
				'email',
             ###'run',
             ###'fNaci',
             ###'telefono',
             ###'region',
             ###'ciudad',
             ###'tipoCasa'
			]
		labels = {
				'username': 'Nombre de usuario',
				'first_name': 'Nombre',
				'last_name': 'Apellidos',
				'email': 'Correo',
                #'run' : 'Run',
                #'fNaci' : 'Fecha nacimiento',
                #'telefono' : 'Telefono',
                #'region' : 'Region',
                #'ciudad' : 'Ciudad',
                #'tipoCasa' : 'Tipo de vivienda',

		}

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index_adopcion(request):
    return HttpResponse("pagina principal de la adopcion")

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView,UpdateView, DeleteView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.

def index(request):
    return render(request, 'mascota/index.html')

def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

apps/usuario/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy

from apps.usuario.forms import RegistroForm

# Create your views here.

class RegistroUsuario(CreateView):
	model = User
	template_name = "usuario/registrar.html"
	form_class =  RegistroForm #UserCreationForm
	success_url = reverse_lazy('mascota:mascota_listar')

blog/views.py
from django.shortcuts import render

def post_list(request):
    return render(request, 'blog/Index.html', {})

blog/templates/blog/Formulario/Form.html
<!DOCTYPE html>
 <html lang="es">
   <head>	
		<link rel="stylesheet" href="estilos.css">
	<!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>-->
    <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" charset="UTF-8" content="width=device-width, initial-scale=1.0"/>
	<title>Contacto "Mis Perris"</title>
		<meta name = "viewport" content = "width = device-width, initial-scale = 1">      
    <link rel = "stylesheet"
		href = "https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel = "stylesheet"
		href = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <script src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js">
    </script> 
	<script>   
		$(document).ready(function() {
			$('select').material_select();
		});
	</script>
    </head>
		
    <body class= "container">
		<header>
			<H1> ¡Hazte Socio! </H1>
		</header>
		<div class="row">
		<form class="col s12">
			<div class="row">
				<div class="input-field col s6">
					<i class="material-icons prefix">perm_identity</i>
					<input id="first_name" type="text" required placeholder="Ingresa primer nombre" title="Solo letras permitidas" pattern="[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]{3,48}" class="validate">
					<label for="first_name">Primer Nombre</label>
				</div>
				<div class="input-field col s6">
					<i class="material-icons prefix">perm_identity</i>
					<input id="first_name1" type="text" required placeholder="Ingresa segundo nombre" title="Solo letras permitidas" pattern="[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]{3,48}" class="validate">
					<label for="first_name1">Segundo Nombre</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<i class="material-icons prefix">perm_identity</i>
					<input id="last_name1" type="text" required placeholder="Ingresa apellido paterno" pattern="[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]{3,48}" class="validate">
					<label for="last_name1">Apellido Paterno</label>
				</div>
				<div class="input-field col s6">
					<i class="material-icons prefix">perm_identity</i>
					<input id="last_name2" type="text" required placeholder="Ingresa apellido materno" pattern="[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]{3,48}" class="validate">
					<label for="last_name2">Apellido Materno</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<i class="material-icons prefix">perm_identity</i>
					<input id="run" type="text" placeholder="Ingresa run. Ej: 19453129-4" required oninput="checkRut(this)" class="validate" maxlength="10">
					<label for="run">Run</label>
					<script src="ValidarRUT.js"></script>
				</div>
				<div class="input-field col s6">
					<i class="material-icons prefix">email</i>
					<input id="email" type="email" required placeholder="Ingrese correo" class="validate">
					<label for="email">Correo</label>
				</div>
			</div>
			<div class = "row">
				<div class="input-field col s6">
					<i class="material-icons prefix">local_phone</i>
					<input id="telefono" type="tel" required placeholder="Ingrese numero telefonico" class="validate" pattern="[0-9]{9}" maxlength="9">
					<label for="telefono">Telefono</label>
				</div>
				<div class="input-field col s12 m6">
					<div class="input-field col s1">
						<i class="material-icons prefix">home</i>
					</div>
					<div class="input-field col s11">
						<select>
							<option value="" disabled selected>Eliga el tipo de Vivienda</option>
							<option value="1">Casa con patio grande</option>
							<option value="2">Casa con patio pequeño</option>
							<option value="3">Casa sin patio</option>
							<option value="4">Departamento</option>
						</select>
						<label>Tipo de Vivienda</label> 
					</div>

				</div>				
            </div>
			<div class="row">
				<div class="input-field col s12 m6">
					<select>
						<option value="" disabled selected>Eliga la región</option>
						<option value="1">Región Metropolitana</option>
						<option value="1">XV Arica y Parinacota</option>
						<option value="1">I Tarapacá</option>
						<option value="1">II Antofagasta</option>
						<option value="1">III Atacama</option>
						<option value="1">IV Coquimbo</option>
						<option value="1">V Valparaíso</option>
						<option value="1">VI O'Higgins</option>
						<option value="1">VII Maule</option>
						<option value="1">VIII Biobío</option>
						<option value="1">IX La Araucanía</option>
						<option value="1">X Los Lagos</option>
						<option value="1">XI Aysén</option>
						<option value="1">XII Magallanes y Antártica</option>
					</select>
					<label>Región</label>
				</div>
				<div class="input-field col s12 m6">
					<select>
						<option value="" disabled selected>Eliga la ciudad</option>
						<option value="1">Arica</option>
						<option value="2">Iquique</option>
						<option value="3">Antofagasta</option>
						<option value="4">Copiapó</option>
						<option value="5">La Serena</option>
						<option value="6">Rancagua</option>
						<option value="7">Talca</option>
						<option value="8">Concepcion</option>
						<option value="9">Temuco</option>
						<option value="10">Valdivia</option>
						<option value="11">Puerto Montt</option>
						<option value="12">Punta Arenas</option>
						<option value="13">Santiago</option>
						<option value="14">Puerto Natales</option>
					</select>
					<label>Ciudad</label>
				</div>
			</div>
			<div class="row">
				<label>Fecha de Nacimiento</label>
				<input type="date" class="datepicker" id="fecha" max="2000-12-31">
			</div>
			<p class="input-field col s6">
				<button class="waves-effect waves-light btn" type="submit"><i class="material-icons right">send</i>enviar</button>
			</p>
		</form>
		</div>
      <!--JavaScript at end of body for optimized loading-->
      <script src="js/materialize.min.js"></script>
      <script>
/*$(function() {
$('#fecha').datepicker({ 
	format: 'dd/mm/yyyy',
	minDate: new Date(2018,12,1) });
});*/
</script>

   </body>
 </html>

blog/templates/blog/Index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Mis perris</title>
	<meta charset="utf-8">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>-->
    <!--Estilos propios.css-->
    <link rel="stylesheet" href="{% static 'css/EstilosPropios.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
</head>
<body>
	<!---->
		<div id="home" class="DivTriple col s12 scrollspy">
        	<a href="" > <img alt="perro" src="{% static 'img/logo.png' %}" ></a>  
     	</div>
	
	 
	
		<div class=" DivTriple col s12">
		  	 <ul class="topnav">
			  <li><a href="#home">inicio</a></li>
			  <li><a href="#rescat">quienes somos</a></li>
			  <li><a href="#servicios">servicios</a></li>
			  <li><a href="#contacto">contáctenos</a></li>
			 </ul>
	 	</div>
	
	<!---->
		<div id="adoptados" class=" DivCarrusel col s12">
      	
				
				<div class="slider" >
				    <ul class="slides">
				    	<li>
				    		<img alt="perro" src="{% static 'img/Tom.jpg' %}"> <!-- random image -->
					        <div class="caption left-align">
					          <h3 class="light light-text ">Tom</h3>

					          <h5 class="light light-text text-lighten-5 " >"Fue una una gran idea adoptarlo".</h5>
					        </div>
				    	</li>
				    	<li>
				    		<img alt="perro" src="{% static 'img/Duque.jpg' %}">
				    		<div class="caption left-align">
					          <h3 class="light light-text ">Duque</h3>

					          <h5 class="light light-text text-lighten-3">"Ahora tengo un mejor amigo".</h5>
					        </div>
				    	</li>
				    	<li>
				    		<div class="caption left-align">
					          <h3 >Apolo</h3>

					          <h5 class="light light-text text-lighten-3 ">"Sé que no me abandonará".</h5>
					        </div>
				    		<img alt="perro" src="{% static 'img/Apolo.jpg' %}">
				    	</li>
				    	
				    </ul>
				</div>

      </div>
	
	<div class="row">
		<div  class=" DivTriple col s12" >

	        <a href="#" > <img alt="face"  class="imgIcono" src="{% static 'img/facebook.png' %}"  ></a>
	        <a href="#" > <img  alt="plus" class="imgIcono" src="{% static 'img/googleplus.png' %}"  ></a>
	        <a href="#" > <img  alt="insta" class="imgIcono" src="{% static 'img/instagram.png' %}"  ></a>
	        <a href="#" > <img  alt="email" class="imgIcono" src="{% static 'img/email.png' %}"  ></a>  
	    </div>
	</div>
	 
	 
    <div class="row">
		<div id="rescat" class=" DivRescate col s12 scrollspy">
	        <div id="cuadroArticle">

	          <section>   
	            <h2>Rescate</h2>
	              <h4>Etapa uno</h4>
	              <p>
	                Rescatamos perros en situación de peligro y/o abandono. Los rehabilitamos y los preparamos para buscarles un lugar.
	              </p>
	              <br>
	              <img alt="rescate" src="{% static 'img/rescate.jpg' %}" >
	          </section>
	        </div>  
      </div>
	</div>
	<div class="row">
		<div id="servicios" class=" DivRescate col s12 scrollspy" >
	        <div id="cuadroArticle2">
	          <section>
	            <img alt="crow" src="{% static 'img/crowfunding.jpg' %}" >
	            <h2>Crowfunding</h2>
	            <h4>Financiamiento</h4>
	            <p>
	              Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para obtener financiamento para seguir ayudando.
	            </p>
	            <br>
	            <a href="" class="boton_2">Campañas</a>
	             
	          </section>
			</div>  
      	</div>
	</div>
      
      
      <div  class=" DivTriple col s12">
          	<div class="row">
          		<div class="col s6 m3"> <!--tarjeta 1-->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Bigotes.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Bigotes<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Bigotes<i class="material-icons right">close</i></span>
				      <p  class="EstiloCard">Es un perro café claro, con grandes bigotes.
				      Perro muy servicial y protector</p>
				    </div>
			  	  </div>
			    </div>
			    <div class="col s6 m3"> <!-- tarjeta 2 -->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Chocolate.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Chocolate<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Chocolate<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es un perro café claro y pelo corto con unas orejas muy grandes</p>
				    </div>
			  	  </div>
			    </div>
			    <div class="col s6 m3"><!-- tarjeta 3 -->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Luna.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Luna<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Luna<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es tiernas y juguetona</p>
				    </div>
			  	  </div>
			    </div>
			    <div class="col s6 m3"><!-- tarjeta 4 -->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Maya.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Maya<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Maya<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es la mas pequeña de todas, de un color café claro con ocico negro, es aún una cachorrita</p>
				    </div>
			  	  </div>
			    </div>

          	</div><!--div del row-->
          	<div class="row">
			    <div class="col s6 m4"> <!--tarjeta 5-->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Oso.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Oso<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Oso<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es un perro de color negro con pintitas café y blancas, es de raza grande, ideal para cuidado de un ambiente grande</p>
				    </div>
			  	  </div>
			    </div>
			    <div class="col s6 m4"> <!-- tarjeta 6 -->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Pexel.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Pexel<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Pexel<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es un perrito crespo de pelo blanco, gran cuidador de niños</p>
				    </div>
			  	  </div>
			    </div>
			    <div class="col s6 m4"><!-- tarjeta 7 -->
			      <div class="card">
				    <div class="card-image waves-effect waves-block waves-light">
				      <img alt="perro" class="activator" src="{% static 'img/Wifi.jpg' %}">
				    </div>
				    <div class="card-content">
				      <span class="card-title activator grey-text text-darken-4">Wifi<i class="material-icons right">more_vert</i></span>
				      
				    </div>
				    <div class="card-reveal">
				      <span class="card-title grey-text text-darken-4">Wifi<i class="material-icons right">close</i></span>
				      <p class="EstiloCard">Es una perrita de pelo corto y liso, con manchas café y blanco, juguetona</p>
				    </div>
			  	  </div>
			    </div>
  			</div><!--div del row-->
      </div><!--div del col s12-->
      <!--Boton flotante-->
	    <div class="fixed-action-btn">
		  <a  target="_blank" class="btn-flat waves-effect waves-red btn-large green" onclick="" href="http://localhost:8000/usuario/registrar/"> ¡Registrate!
		  	<!--<a  target="_blank" class="btn-floating btn-large green" onclick="location.href='https://www.facebook.com'">-->
		    <i class="large material-icons">fingerprint</i>
			</a>
			<a  target="_blank" class="btn-flat waves-effect waves-red btn-large green" onclick="" href="http://localhost:8000/admin"> Inicia Sesión
		  	<!--<a  target="_blank" class="btn-floating btn-large green" onclick="location.href='https://www.facebook.com'">-->
		    <i class="large material-icons">fingerprint</i>
		  </a>
		</div>
	      <div  class="DivFooter col s12">Desarrollo web y mobile</div>
	   
    	
		
      <!--JavaScript at end of body for optimized loading-->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

      <script  src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

      <script  src="{% static 'js/materialize.min.js' %}"></script>
	  
	  
      <script>
		$(document).ready(function(){
			$('.slider').slider({
				full_width:true,
				full_height: true
			});
			$('.scrollspy').scrollSpy();
			$('.materialbox').materialbox();
			$('.fixed-action-btn').floatingActionButton();})</script>

</body>
</html>

templates/login.html
{% extends 'base/base.html' %}

{% block title %}
Mascotas
{% endblock %}
{% block navbar%}
{% endblock %}
{% block content %}
<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>    
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
					<a href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>


{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Raza</td>
			<td>Sexo</td>
			<td>Descripcion</td>
            <td>Estado</td>
            <td>Adoptante</td>
            <td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td>{{ mascota.id }}</td>
			<td>{{ mascota.nombre }}</td>
			<td>{{ mascota.raza }}</td>
			<td>{{ mascota.sexo }}</td>
            <td>{{ mascota.descripcion }}</td>
            <td>{{ mascota.estado }}</td>
            <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
            <td>       
                <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
            </td>
            
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de mascotas</h1>
		{% endif %}
	</tbody>
</table> 

{% endblock%}